name: exammate
description: A competitive exam planner app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

# Configuration for App Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

# Configuration for Native Splash Screen
flutter_native_splash:
  color: "#121212"        # Keep your dark background color

  # image: "assets/icon/splash.png"  <-- COMMENT THIS OUT

  # Comment out the Android 12 section too

  # android_12:
  #   image: "assets/icon/splash.png"
  #   color: "#121212"

flutter:

  uses-material-design: true

  

  assets:

    - assets/sounds/bell.mp3  # <--- Add this line